import json
import re
from tools.product_tools import find_product_tool
from tools.cart_tools import create_cart, add_item, change_quantity, calculate_total
from .runtime import crew_json
from .crewai_tools import get_product_tools


def _fallback_extract(text, catalog):
    q = (text or "").lower()
    found = []
    for p in catalog:
        aliases = [p["name"].lower()] + [a.strip().lower() for a in str(p.get("aliases", "")).split(",") if a.strip()]
        matched = next((a for a in aliases if a and a in q), None)
        if not matched:
            continue
        # Supports "2 Pepsi", "Pepsi x 2", and "Pepsi 2" patterns.
        patterns = [
            rf"(\d+(?:\.\d+)?)\s*(?:x|×)?\s*{re.escape(matched)}",
            rf"{re.escape(matched)}\s*(?:x|×)?\s*(\d+(?:\.\d+)?)",
        ]
        qty = 1.0
        for pattern in patterns:
            m = re.search(pattern, q)
            if m:
                qty = float(m.group(1))
                break
        found.append({"product_id": p["id"], "quantity": qty})
    return {"items": found}


def extract_order(text: str, business_id: int = 1) -> dict:
    from database import list_products
    catalog = [
        {"id": p["id"], "name": p["name"], "aliases": p.get("aliases", ""), "unit": p.get("unit", "unit")}
        for p in list_products(business_id)
    ]
    fallback = _fallback_extract(text, catalog)
    prompt = f"""Extract a shop order into JSON. Use ONLY product IDs from this catalogue:
{json.dumps(catalog, ensure_ascii=False)}
Support Urdu/Roman Urdu/English. Quantity must be numeric and greater than zero.
Return only {{"items":[{{"product_id":1,"quantity":2}}]}}.
Order: {text}"""
    data = crew_json(
        "Smart Sale Agent",
        "Extract products and quantities from a natural-language order without inventing products or prices.",
        "You are a sales extraction specialist. Product identity must come from the supplied catalogue. Prices are never generated by you.",
        prompt,
        fallback=fallback,
        tools=get_product_tools(),
    )
    products = []
    valid_ids = {p["id"]: p for p in catalog}
    for item in data.get("items", []) if isinstance(data, dict) else []:
        try:
            pid = int(item["product_id"])
            qty = float(item["quantity"])
        except (KeyError, TypeError, ValueError):
            continue
        if pid in valid_ids and qty > 0:
            products.append({"product": valid_ids[pid], "quantity": qty})
    return {"items": products}


def build_cart(text: str, business_id: int = 1) -> dict:
    parsed = extract_order(text, business_id)
    cart = create_cart()
    for item in parsed["items"]:
        product = find_product_tool(item["product"]["name"], business_id)
        if product:
            add_item(cart, product, item["quantity"])
    return {"cart": cart, "total": calculate_total(cart)}


def apply_cart_edit(cart, action: str, business_id: int = 1) -> dict:
    parsed = extract_order(action, business_id)
    if not parsed["items"]:
        return {"cart": cart, "total": calculate_total(cart), "changed": False}
    for item in parsed["items"]:
        pid = item["product"]["id"]
        existing = next((x for x in cart if x["product_id"] == pid), None)
        if existing:
            change_quantity(cart, pid, item["quantity"])
        else:
            add_item(cart, find_product_tool(item["product"]["name"], business_id), item["quantity"])
    return {"cart": cart, "total": calculate_total(cart), "changed": True}
